version: '3.8'

services:
  
  backend:
    build:
      context: ./backend2
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb+srv://devsurajkadam:3YGT4wLqEV5bbNdU@cluster0.yrfn57v.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    volumes:
      - ./frontend:/app
    restart: always
    depends_on:
      - backend

  backend1:
    build:
      context: ./backend1
    ports:
      - "5005:5005"
    environment:
      - MONGO_URI=mongodb+srv://devsurajkadam:3YGT4wLqEV5bbNdU@cluster0.yrfn57v.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - ./backend1:/app
    restart: always

  frontend1:
    build:
      context: ./frontend1
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./frontend1:/app
    restart: always
    depends_on:
      - backend1
