name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect and deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 43.204.228.100
          username: ec2-user  # or ubuntu if you're using Ubuntu AMI
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/Webhook
            git pull origin main
            echo "the code is deploy"
